In [17]:
kernel = [[0.12, 0.14, 0.22], [0.91, 0.44, 0.31], [0.77, 0.51, 0.13]]
kernel

[[0.12, 0.14, 0.22], [0.91, 0.44, 0.31], [0.77, 0.51, 0.13]]

In [18]:
image = [[0.5, 0.5, 0.3, 0.2, 0.1], [0.3, 0.2, 0.8, 0.9, 1.0], [0.7, 0.7, 0.5, 1.0, 1.0], [0.6, 0.6, 0.4, 0.9, 1.0], [0.1, 0.4, 0.6, 0.7, 0.8]]
image


[[0.5, 0.5, 0.3, 0.2, 0.1],
 [0.3, 0.2, 0.8, 0.9, 1.0],
 [0.7, 0.7, 0.5, 1.0, 1.0],
 [0.6, 0.6, 0.4, 0.9, 1.0],
 [0.1, 0.4, 0.6, 0.7, 0.8]]

In [19]:
import numpy as np

In [20]:
image = np.array(image)
kernel = np.array(kernel)

kernel

array([[0.12, 0.14, 0.22],
       [0.91, 0.44, 0.31],
       [0.77, 0.51, 0.13]])

In [21]:
subset = image[0:3, 0:3]
subset

array([[0.5, 0.5, 0.3],
       [0.3, 0.2, 0.8],
       [0.7, 0.7, 0.5]])

In [22]:
out = np.multiply(subset, kernel)
out

array([[0.06 , 0.07 , 0.066],
       [0.273, 0.088, 0.248],
       [0.539, 0.357, 0.065]])

In [23]:
out = np.sum(out)
out

1.766

In [26]:
image[0:3,4:7]

array([[0.1],
       [1. ],
       [1. ]])